### PR TITLE
Navigation bar

### PR DESCRIPTION
**Pull request by mackenziekerwin**
Responsive nav bar!
It's kind of primitive--I'm not sure if there should be any special sliding animations on mobile but I haven't done that. Also, not sure if the content behind the menu should be scrollable/clickable when it's open on tablet.
## Figma
Desktop:
Screen Shot 2022-04-15 at 1 38 23 PM

Tablet:
Screen Shot 2022-04-15 at 1 38 45 PM
Screen Shot 2022-04-15 at 1 38 58 PM

Mobile:
Screen Shot 2022-04-15 at 1 39 10 PM
Screen Shot 2022-04-15 at 1 39 17 PM

### CODE REVIEW

**Review by gabbybruck — COMMENTED** [review]
It looks so good!! One small thing I noticed is that when I mouse over the close button on the mobile menu, the cursor turns back to a pointer instead of the eyeball

**Review by gabbybruck — APPROVED** [review]

**Review by mnav0 — COMMENTED** [review]
this looks great! one thing, when i open the menu on tablet or mobile i can't click the x to close it (the cursor never turns to the custom pointer and clicking does nothing)

**Comment by mackenziekerwin** [comment]
> this looks great! one thing, when i open the menu on tablet or mobile i can't click the x to close it (the cursor never turns to the custom pointer and clicking does nothing)

try it now! I adjusted the cursor's hotspot to the center of the circle--I think the x button is small enough that when the hotspot was in the top left you had to click a little bit to the right of the x to close it. it's working better for me but lmk if it still doesn't work for you

**Review by mnav0 — APPROVED** [review]
lgtm! one more thing can you fix this error from a previous PR before you merge??

Screen Shot 2022-04-19 at 1 22 52 PM

**Pull request merged**
